name: Download and Show File Content

on:
  workflow_dispatch:

jobs:
  download-file:
    name: download-and-show-file
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > sample.txt
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: sample.txt
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
        
      - name: Show file content
        run: cat sample.txt
          