name: Echo Test

on:
  workflow_dispatch:

jobs:
  generate-secret:
    runs-on: ubuntu-latest
    outputs:
      secret: ${{ steps.sets-a-secret.outputs.secret-number }}    
    steps:
      - id: sets-a-secret
        name: Generate, mask, and output a secret
        run: |
          the_secret=$((RANDOM))
          echo "::add-mask::$the_secret"
          echo "secret-number=$the_secret" >> "$GITHUB_OUTPUT"
          cat $GITHUB_OUTPUT
      - name: Use that secret output (protected by a mask)
        run: |
          echo "the secret number is ${{ steps.sets-a-secret.outputs.secret-number }}"
  use-secret:
    runs-on: ubuntu-latest
    needs: generate-secret
    steps:
    - name: Use the Generated Secret
      run: |
        echo "Using the secret from the previous job"
        #RETRIEVED_SECRET=${{ needs.generate-secret.outputs.secret }}
        RETRIEVED_SECRET=${{ jobs.generate-secret.outputs.secret }}
        RETRIEVED_SECRET1=${{ jobs.previous_job_id.outputs.secret }}
        echo "RETRIEVED_SECRET 01=$RETRIEVED_SECRET"
        echo "RETRIEVED_SECRET1 01=$RETRIEVED_SECRET1"
        echo "::add-mask::$RETRIEVED_SECRET"
        echo "We retrieved our masked secret: $RETRIEVED_SECRET"
        
      
