name: Download and Show File Content

on:
  workflow_dispatch:

jobs:
  upload-file:
    name: upload-file
    runs-on: ubuntu-latest
    steps:
      - name: Prepare sample.txt
        run: |
          expr 1 + 1 > sample.txt
          ls
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: sample.txt
  download-file:
    name: download-and-show-file
    runs-on: ubuntu-latest
    steps:
      - name: Show Directory
        run: |
          ls
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: my-artifact
      - name: Show file content
        run: cat sample.txt