name: MY Upload

on:
  workflow_dispatch:

jobs:
  upload-file:
    name: upload-file
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Prepare sample.txt
        run: |
          expr 1 + 1 > sample.txt
          ls
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: sample.txt
          
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Download and Install MPI HDF5 CGNS METIS          